### ISSUE TITLE
ERROR: Unable to acquire cookie.

### ISSUE THREAD

**Issue by alexsahka** [atoy3731/adguard-sync#11]
It worked for a long time, thank you very much, and then I noticed that it stopped synchronizing with an error:

ERROR: Unable to acquire cookie.
Message: only content-type application/json is allowed

All 3 containers are the latest.

**Comment by alexsahka** [comment]
find the problem

**Comment by JimmyAllnighter** [comment]
@alexsahka - Please elaborate.

Raising an issue like this, then closing without explanation is [one of the worst things](https://xkcd.com/979) you can do as both a user and a developer.

It doesn't matter how seemingly straightforward the solution is, just post it for the benefit of others before closing.

**Comment by alexsahka** [comment]
I stated that --- All 3 containers are the latest.

But mysteriously, one of the containers was not updated to the latest
After updating to the latest, everything starts synchronizing as it should.

Wanted to delete this issue but wasn't able for some reason. My mistake who needs this?

**Comment by JimmyAllnighter** [comment]
Thank you for providing more context (and so quickly!).

Even though it's closed, please leave this issue up for others that may encounter this problem in the future - it may appear in Google search results.

Thanks again, and happy holidays :)
