### ISSUE TITLE
Configs Sync

### ISSUE THREAD

**Issue by gabriel-vanca** [atoy3731/adguard-sync#3]
It would be great if this could sync the settings of each deployment as well rather than just the blacklists/whitelists.

**Comment by atoy3731** [comment]
Great idea for a feature request. I just merged in the ability to sync all Filter elements (rewrites, allow/block lists, blocked services, and custom rules ([link](https://github.com/atoy3731/adguard-sync/releases/tag/2.0)), but keeping settings in sync would also be very beneficial.

Given settings are somewhat module, is there any particular settings you'd want prioritized over others?
